// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfajjqeixzikmvuitmcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmYWpqcWVpeHppa212dWl0bWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNjM4ODQsImV4cCI6MjA2MjgzOTg4NH0.lSajZpFv_P5squjiVR-q1Pze6TNTIdXnYXH3UCN04Yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);